import { prisma } from '../services/prisma.service';

/**
 * Real, Authentic Maharashtra Gram Panchayat Villages mapped to Districts & Talukas
 */
export const PROPER_TALUKA_VILLAGES: Record<string, Array<{ en: string; mr: string; hi?: string }>> = {
  // ── Pune District ──────────────────────────────────────────────────────────
  haveli: [
    { en: 'Wagholi', mr: 'वाघोली' },
    { en: 'Uruli Kanchan', mr: 'उरुळी कांचन' },
    { en: 'Loni Kalbhor', mr: 'लोणी काळभोर' },
    { en: 'Theur', mr: 'थेऊर' },
    { en: 'Manjari Budruk', mr: 'मांजरी बुद्रुक' },
    { en: 'Kesnand', mr: 'केसनंद' },
    { en: 'Khadakwasla', mr: 'खडकवासला' },
    { en: 'Kirkatwadi', mr: 'किरकटवाडी' },
    { en: 'Nanded City', mr: 'नांदेड सिटी' },
    { en: 'Shivane', mr: 'शिवणे' },
    { en: 'Kondhwa Budruk', mr: 'कोंढवा बुद्रुक' },
    { en: 'Uttamnagar', mr: 'उत्तमनगर' },
    { en: 'Donje (Sinhagad)', mr: 'डोणजे (सिंहगड)' },
    { en: 'Khanapur', mr: 'खानापूर' },
    { en: 'Gorhe Budruk', mr: 'गोरहे बुद्रुक' },
    { en: 'Koregaon Bhima', mr: 'कोरेगाव भीमा' },
    { en: 'Lohegaon Gramin', mr: 'लोहगाव ग्रामीण' },
    { en: 'Hadapsar Gramin', mr: 'हडपसर ग्रामीण' },
  ],
  baramati: [
    { en: 'Malegaon Budruk', mr: 'माळेगाव बुद्रुक' },
    { en: 'Malegaon Khurd', mr: 'माळेगाव खुर्द' },
    { en: 'Supe', mr: 'सुपे' },
    { en: 'Pimpali', mr: 'पिंपळी' },
    { en: 'Korhale Budruk', mr: 'कोऱ्हाळे बुद्रुक' },
    { en: 'Undawadi Supe', mr: 'उंडवडी सुपे' },
    { en: 'Undawadi K.P.', mr: 'उंडवडी के.पी.' },
    { en: 'Karanje', mr: 'करंजे' },
    { en: 'Parawadi', mr: 'पारवडी' },
    { en: 'Songaon', mr: 'सोनगाव' },
    { en: 'Shirsuphal', mr: 'शिरसुफळ' },
    { en: 'Morgaon', mr: 'मोरगाव' },
    { en: 'Dorlewadi', mr: 'डोर्लेवाडी' },
    { en: 'Rui', mr: 'रुई' },
    { en: 'Katewadi', mr: 'काटेवाडी' },
    { en: 'Kanheri', mr: 'कन्हेरी' },
    { en: 'Medad', mr: 'मेढद' },
    { en: 'Late', mr: 'लाटे' },
    { en: 'Hol', mr: 'होळ' },
  ],
  indapur: [
    { en: 'Nimgaon Ketki', mr: 'निमगाव केतकी' },
    { en: 'Bawada', mr: 'बावडा' },
    { en: 'Bhigwan', mr: 'भिगवण' },
    { en: 'Kumbhargaon', mr: 'कुंभारगाव' },
    { en: 'Anthurne', mr: 'अंथुर्णे' },
    { en: 'Shelgaon', mr: 'शेलगाव' },
    { en: 'Palasdeo', mr: 'पळसदेव' },
    { en: 'Varkute', mr: 'वरकुटे' },
    { en: 'Loni Deokar', mr: 'लोणी देवकर' },
    { en: 'Kalthan', mr: 'कळठण' },
    { en: 'Bori', mr: 'बोरी' },
    { en: 'Sansar', mr: 'संसार' },
    { en: 'Belwadi', mr: 'बेलवाडी' },
    { en: 'Lasurne', mr: 'लसुर्णे' },
    { en: 'Nimaj', mr: 'निमज' },
  ],
  shirur: [
    { en: 'Ranjangaon Ganpati', mr: 'रांजणगाव गणपती' },
    { en: 'Shikrapur', mr: 'शिक्रापूर' },
    { en: 'Talegaon Dhamdhere', mr: 'तळेगाव ढमढेरे' },
    { en: 'Koregaon Bhima', mr: 'कोरेगाव भीमा' },
    { en: 'Sanaswadi', mr: 'सणसवाडी' },
    { en: 'Pabal', mr: 'पाबळ' },
    { en: 'Mandavgan Farata', mr: 'मांडवगण फराटा' },
    { en: 'Nhavare', mr: 'न्हावरे' },
    { en: 'Nimgaon Mhalungi', mr: 'निमगाव म्हाळुंगी' },
    { en: 'Kavathe Yemai', mr: 'कवठे येमाई' },
    { en: 'Wadgaon Rasai', mr: 'वडगाव रासाई' },
    { en: 'Inamgaon', mr: 'इनामगाव' },
    { en: 'Tardobachiwadi', mr: 'तारडोबाचीवाडी' },
  ],
  junnar: [
    { en: 'Narayangaon', mr: 'नारायणगाव' },
    { en: 'Otur', mr: 'ओतूर' },
    { en: 'Alephata', mr: 'आळेफाटा' },
    { en: 'Rajuri', mr: 'राजुरी' },
    { en: 'Aptale', mr: 'आपटाळे' },
    { en: 'Dingore', mr: 'डिंगोरे' },
    { en: 'Khamgaon', mr: 'खामगाव' },
    { en: 'Pimpalwandi', mr: 'पिंपळवंडी' },
    { en: 'Kusur', mr: 'कुसूर' },
    { en: 'Belhe', mr: 'बेल्हे' },
    { en: 'Madh', mr: 'मढ' },
    { en: 'Bori Budruk', mr: 'बोरी बुद्रुक' },
    { en: 'Manikdoh', mr: 'माणिकडोह' },
  ],
  khed: [
    { en: 'Chakan Gramin', mr: 'चाकण ग्रामीण' },
    { en: 'Alandi Gramin', mr: 'आळंदी ग्रामीण' },
    { en: 'Rajgurunagar (Khed)', mr: 'राजगुरुनगर (खेड)' },
    { en: 'Wada', mr: 'वाडा' },
    { en: 'Kadus', mr: 'कडूस' },
    { en: 'Chas', mr: 'चास' },
    { en: 'Shelgaon', mr: 'शेलगाव' },
    { en: 'Medankarwadi', mr: 'मेदणकरवाडी' },
    { en: 'Kuruli', mr: 'कुरुळी' },
    { en: 'Khalumbre', mr: 'खळुंब्रे' },
    { en: 'Nanekarwadi', mr: 'नाणेकरवाडी' },
    { en: 'Bahul', mr: 'बाहुळ' },
    { en: 'Kharpudi', mr: 'खरपुडी' },
  ],
  daund: [
    { en: 'Patas', mr: 'पाटस' },
    { en: 'Kedgaon', mr: 'केडगाव' },
    { en: 'Kurkumbh', mr: 'कुरकुंभ' },
    { en: 'Bori Bhadak', mr: 'बोरी भडक' },
    { en: 'Yavat', mr: 'यवत' },
    { en: 'Varwand', mr: 'वरवंड' },
    { en: 'Boripardhi', mr: 'बोरीपार्धी' },
    { en: 'Khadki Daund', mr: 'खडकी दौंड' },
    { en: 'Malad', mr: 'मालाड' },
    { en: 'Ravangaon', mr: 'रावणगाव' },
    { en: 'Girim', mr: 'गिरीम' },
    { en: 'Kangaon', mr: 'कानगाव' },
  ],
  purandar: [
    { en: 'Saswad Gramin', mr: 'सासवड ग्रामीण' },
    { en: 'Jejuri Gramin', mr: 'जेजुरी ग्रामीण' },
    { en: 'Belsar', mr: 'बेलसर' },
    { en: 'Dive', mr: 'दिवे' },
    { en: 'Chambhli', mr: 'चांभळी' },
    { en: 'Pisarve', mr: 'पिसर्वे' },
    { en: 'Walha', mr: 'वाल्हा' },
    { en: 'Parinche', mr: 'परिंचे' },
    { en: 'Garade', mr: 'गराडे' },
    { en: 'Singapur', mr: 'सिंगापूर' },
    { en: 'Pingori', mr: 'पिंगोरी' },
    { en: 'Sonori', mr: 'सोनोरी' },
  ],
  maval: [
    { en: 'Talegaon Dabhade Gramin', mr: 'तळेगाव दाभाडे ग्रामीण' },
    { en: 'Lonavala Gramin', mr: 'लोणावळा ग्रामीण' },
    { en: 'Kamshet', mr: 'कामशेत' },
    { en: 'Wadgaon Maval', mr: 'वडगाव मावळ' },
    { en: 'Karla', mr: 'कार्ला' },
    { en: 'Malavli', mr: 'मळवली' },
    { en: 'Kusgaon', mr: 'कुसगाव' },
    { en: 'Takve Budruk', mr: 'ताकवे बुद्रुक' },
    { en: 'Somatane', mr: 'सोमाटणे' },
    { en: 'Shirgaon', mr: 'शिरगाव' },
    { en: 'Pawananagar', mr: 'पवनानगर' },
  ],
  mulshi: [
    { en: 'Paud', mr: 'पौड' },
    { en: 'Pirangut', mr: 'पिरंगुट' },
    { en: 'Hinjawadi Gramin', mr: 'हिंजवडी ग्रामीण' },
    { en: 'Lavale', mr: 'लवाळे' },
    { en: 'Sus', mr: 'सूस' },
    { en: 'Kasar Amboli', mr: 'कासार आंबोली' },
    { en: 'Kolwan', mr: 'कोळवण' },
    { en: 'Marunji', mr: 'मारुंजी' },
    { en: 'Nande', mr: 'नांदे' },
    { en: 'Rihe', mr: 'रिहे' },
    { en: 'Mutha', mr: 'मुठा' },
    { en: 'Shere', mr: 'शेरे' },
  ],
  ambegaon: [
    { en: 'Manchar', mr: 'मंचर' },
    { en: 'Ghodegaon', mr: 'घोडेगाव' },
    { en: 'Kalamb', mr: 'कळंब' },
    { en: 'Shinoli', mr: 'शिनोली' },
    { en: 'Dimbhe', mr: 'डिंभे' },
    { en: 'Pargaon', mr: 'पारगाव' },
    { en: 'Awasari Budruk', mr: 'अवसरी बुद्रुक' },
    { en: 'Awasari Khurd', mr: 'अवसरी खुर्द' },
    { en: 'Nirgudsar', mr: 'निरगुडसर' },
    { en: 'Mahalunge Padwal', mr: 'म्हाळुंगे पडवळ' },
    { en: 'Shingave', mr: 'शिंगवे' },
    { en: 'Taleghar', mr: 'तळेघर' },
  ],

  // ── Nashik District ────────────────────────────────────────────────────────
  niphad: [
    { en: 'Pimpalgaon Baswant', mr: 'पिंपळगाव बसवंत' },
    { en: 'Lasalgaon', mr: 'लासलगाव' },
    { en: 'Vinchur', mr: 'विंचूर' },
    { en: 'Chandori', mr: 'चांदोरी' },
    { en: 'Saikheda', mr: 'सायखेडा' },
    { en: 'Ranwad', mr: 'रानवड' },
    { en: 'Kundewadi', mr: 'कुंदेवाडी' },
    { en: 'Devgaon', mr: 'देवगाव' },
    { en: 'Ozar Mig', mr: 'ओझर मिग' },
    { en: 'Khedgaon', mr: 'खेडगाव' },
    { en: 'Pimpalas', mr: 'पिंपळास' },
    { en: 'Shirwade Vani', mr: 'शिरवाडे वणी' },
  ],
  dindori: [
    { en: 'Vani', mr: 'वणी' },
    { en: 'Dindori Center', mr: 'दिंडोरी केंद्र' },
    { en: 'Ozar Rural', mr: 'ओझर ग्रामीण' },
    { en: 'Mhasrul', mr: 'म्हसरुळ' },
    { en: 'Nanashi', mr: 'नानाशी' },
    { en: 'Umrale', mr: 'उमराळे' },
    { en: 'Janori', mr: 'जानोरी' },
    { en: 'Koshimbe', mr: 'कोशिंबे' },
    { en: 'Karanjali', mr: 'करंजाळी' },
    { en: 'Varkheda', mr: 'वरखेडा' },
  ],
  sinnar: [
    { en: 'Musalgaon', mr: 'मुसळगाव' },
    { en: 'Pandhurli', mr: 'पांढुर्ली' },
    { en: 'Dapur', mr: 'दापूर' },
    { en: 'Vavi', mr: 'वावी' },
    { en: 'Dubere', mr: 'डुबेरे' },
    { en: 'Naigaon Sinnar', mr: 'नायगाव सिन्नर' },
    { en: 'Wadgaon Sinnar', mr: 'वडगाव सिन्नर' },
    { en: 'Pangri Sinnar', mr: 'पांगरी सिन्नर' },
    { en: 'Shinde', mr: 'शिंदे' },
    { en: 'Baragaon Pimpri', mr: 'बारागाव पिंप्री' },
  ],
  malegaon: [
    { en: 'Ravanje', mr: 'रावेणजे' },
    { en: 'Wadner Malegaon', mr: 'वडनेर मालेगाव' },
    { en: 'Chandanpuri', mr: 'चंदनपुरी' },
    { en: 'Sayane', mr: 'सायाने' },
    { en: 'Zodge', mr: 'झोडगे' },
    { en: 'Dabhadi', mr: 'दाभाडी' },
    { en: 'Nimgaon Malegaon', mr: 'निमगाव मालेगाव' },
    { en: 'Soundane', mr: 'सौंदाणे' },
    { en: 'Chikhalohol', mr: 'चिखलोहोळ' },
  ],
  yeola: [
    { en: 'Andarsul', mr: 'अंदरसूल' },
    { en: 'Nagarsul', mr: 'नगरसूल' },
    { en: 'Patoda Yeola', mr: 'पाटोदा येवला' },
    { en: 'Erandgaon', mr: 'एरंडगाव' },
    { en: 'Rajaigaon', mr: 'राजाईगाव' },
    { en: 'Mukhed Yeola', mr: 'मुखेड येवला' },
    { en: 'Angangaon', mr: 'अंगणगाव' },
    { en: 'Paregaon', mr: 'पारेगाव' },
    { en: 'Kotamgaon', mr: 'कोटमगाव' },
  ],
  chandwad: [
    { en: 'Vadner Bhairao', mr: 'वडनेर भैरव' },
    { en: 'Rahud', mr: 'राहुड' },
    { en: 'Mangrul', mr: 'मंगरूळ' },
    { en: 'Dhotane', mr: 'धोटाणे' },
    { en: 'Usward', mr: 'उसवाड' },
    { en: 'Kundalgaon', mr: 'कुंदलगाव' },
    { en: 'Shirasgaon Chandwad', mr: 'शिरसगाव चांदवड' },
  ],

  // ── Ahilyanagar (Ahmednagar) District ──────────────────────────────────────
  shrirampur: [
    { en: 'Belapur', mr: 'बेलापूर' },
    { en: 'Puntamba', mr: 'पुणतांबा' },
    { en: 'Taklibhan', mr: 'टाकळीभान' },
    { en: 'Nipani Wadgaon', mr: 'निपाणी वडगाव' },
    { en: 'Malunja', mr: 'माळुंजा' },
    { en: 'Padhegaon', mr: 'पाढेगाव' },
    { en: 'Matapur', mr: 'मातापूर' },
    { en: 'Galnimb', mr: 'गळनिंब' },
  ],
  rahata: [
    { en: 'Shirdi Gramin', mr: 'शिर्डी ग्रामीण' },
    { en: 'Sakori', mr: 'साकोरी' },
    { en: 'Pimplas', mr: 'पिंपळास' },
    { en: 'Korhale', mr: 'कोऱ्हाळे' },
    { en: 'Astagaon', mr: 'अस्तागाव' },
    { en: 'Babhaleshwar', mr: 'बाभळेश्वर' },
    { en: 'Loni Budruk', mr: 'लोणी बुद्रुक' },
    { en: 'Loni Khurd', mr: 'लोणी खुर्द' },
    { en: 'Kelwad', mr: 'केळवड' },
    { en: 'Rui Rahata', mr: 'रुई राहाता' },
    { en: 'Ekrukhe', mr: 'एकरुखे' },
  ],
  sangamner: [
    { en: 'Ashwi Budruk', mr: 'आश्वी बुद्रुक' },
    { en: 'Ashwi Khurd', mr: 'आश्वी खुर्द' },
    { en: 'Jorve', mr: 'जोर्वे' },
    { en: 'Ghargaon', mr: 'घारगाव' },
    { en: 'Samnapur', mr: 'सामनापूर' },
    { en: 'Chandnapuri', mr: 'चंदनापुरी' },
    { en: 'Talegaon Digras', mr: 'तळेगाव दिग्रस' },
    { en: 'Sakur', mr: 'साकूर' },
    { en: 'Nimgaon Jali', mr: 'निमगाव जाळी' },
    { en: 'Pemgiri', mr: 'पेमगिरी' },
  ],
  kopargaon: [
    { en: 'Pohegaon', mr: 'पोहेगाव' },
    { en: 'Dhamori', mr: 'धामोरी' },
    { en: 'Kolpewadi', mr: 'कोलपेवाडी' },
    { en: 'Ravande', mr: 'रवांदे' },
    { en: 'Sanvatsar', mr: 'संवत्सर' },
    { en: 'Yesgaon', mr: 'येसगाव' },
    { en: 'Shingnapur Kopargaon', mr: 'शिंगणापूर कोपरगाव' },
    { en: 'Dahigaon Bolka', mr: 'दहिगाव बोलका' },
  ],
  shevgaon: [
    { en: 'Bodhegaon', mr: 'बोधेगाव' },
    { en: 'Chapdgaon', mr: 'चापडगाव' },
    { en: 'Mungi', mr: 'मुंगी' },
    { en: 'Hatgaon', mr: 'हातगाव' },
    { en: 'Erandgaon Shevgaon', mr: 'एरंडगाव शेवगाव' },
    { en: 'Dahigaon Ne', mr: 'दहिगाव ने' },
    { en: 'Joharapur', mr: 'जव्हारापूर' },
    { en: 'Varur', mr: 'वरूर' },
  ],
  nevasa: [
    { en: 'Shani Shingnapur', mr: 'शनि शिंगणापूर' },
    { en: 'Sonai', mr: 'सोनाई' },
    { en: 'Kukana', mr: 'कुकणा' },
    { en: 'Bhenda', mr: 'भेंडा' },
    { en: 'Ghogargaon', mr: 'घोगरगाव' },
    { en: 'Devgaon Nevasa', mr: 'देवगाव नेवासा' },
    { en: 'Salabatpur', mr: 'सलाबतपूर' },
    { en: 'Pravarasangam', mr: 'प्रवरासंगम' },
    { en: 'Wadala Bahiroba', mr: 'वडाळा बहिरोबा' },
  ],
  parner: [
    { en: 'Ralegan Siddhi', mr: 'राळेगण सिद्धी' },
    { en: 'Supe Parner', mr: 'सुपे पारनेर' },
    { en: 'Takli Dhokeshwar', mr: 'टाकळी ढोकेश्वर' },
    { en: 'Alkuti', mr: 'आळकुटी' },
    { en: 'Nighoj', mr: 'निघोज' },
    { en: 'Wadgaon Darya', mr: 'वडगाव दर्या' },
    { en: 'Kanhur Pathar', mr: 'कान्हूर पठार' },
  ],
  nagar: [
    { en: 'Bhingar', mr: 'भिंगार' },
    { en: 'Nagardeole', mr: 'नगरदेवळे' },
    { en: 'Chas Nagar', mr: 'चास नगर' },
    { en: 'Jeur Nagar', mr: 'जेऊर नगर' },
    { en: 'Burhannagar', mr: 'बुर्‍हाणनगर' },
    { en: 'Arangaon', mr: 'अरणगाव' },
    { en: 'Kapurwadi', mr: 'कपूरवाडी' },
    { en: 'Walki', mr: 'वाळकी' },
    { en: 'Nimblak', mr: 'निंबळक' },
    { en: 'Islak', mr: 'इस्लाक' },
  ],
  rahuri: [
    { en: 'Vambori', mr: 'वांबोरी' },
    { en: 'Kolhar', mr: 'कोल्हार' },
    { en: 'Deolali Pravara', mr: 'देवळाली प्रवरा' },
    { en: 'Guha', mr: 'गुहा' },
    { en: 'Brahmani', mr: 'ब्राह्मणी' },
    { en: 'Songaon Rahuri', mr: 'सोनगाव राहुरी' },
    { en: 'Taharabad', mr: 'तहाराबाद' },
  ],
  shrigonda: [
    { en: 'Belwandi', mr: 'बेलवंडी' },
    { en: 'Pedgaon', mr: 'पेडगाव' },
    { en: 'Kashti', mr: 'काष्टी' },
    { en: 'Mandavgan Shrigonda', mr: 'मांडवगण श्रीगोंदा' },
    { en: 'Kolgaon Shrigonda', mr: 'कोलगाव श्रीगोंदा' },
    { en: 'Chimbhale', mr: 'चिंभळे' },
    { en: 'Limpangaon', mr: 'लिंपणगाव' },
  ],
  karjat_a: [
    { en: 'Rashin', mr: 'राशिन' },
    { en: 'Mirajgaon', mr: 'मिरजगाव' },
    { en: 'Mahi Jalgaon', mr: 'माही जळगाव' },
    { en: 'Koregaon Karjat', mr: 'कोरेगाव कर्जत' },
    { en: 'Kombhali', mr: 'कोंभाळी' },
    { en: 'Durgaon', mr: 'दुरगाव' },
    { en: 'Benwadi', mr: 'बेनवाडी' },
  ],
  jamkhed: [
    { en: 'Kharda', mr: 'खर्डा' },
    { en: 'Nanaj', mr: 'नान्नज' },
    { en: 'Arvi Jamkhed', mr: 'आर्वी जामखेड' },
    { en: 'Saundana', mr: 'सौंदाणा' },
    { en: 'Chumbhali', mr: 'चुंभळी' },
    { en: 'Ratnapur Jamkhed', mr: 'रत्नापूर जामखेड' },
  ],

  // ── Solapur District ───────────────────────────────────────────────────────
  pandharpur: [
    { en: 'Bhalwani', mr: 'भालवणी' },
    { en: 'Kasegaon Pandharpur', mr: 'कासेगाव पंढरपूर' },
    { en: 'Tungat', mr: 'तुंगत' },
    { en: 'Korti Pandharpur', mr: 'कोर्टी पंढरपूर' },
    { en: 'Gadegaon', mr: 'गादेगाव' },
    { en: 'Isbavi', mr: 'इसबावी' },
    { en: 'Tarapur', mr: 'तारापूर' },
    { en: 'Tavshi', mr: 'तावशी' },
    { en: 'Puluj', mr: 'पुलूज' },
    { en: 'Karkamb', mr: 'करकंब' },
    { en: 'Wakhari', mr: 'वाखरी' },
    { en: 'Bhatumbre', mr: 'भातुंबरे' },
    { en: 'Shegaon Dhumal', mr: 'शेगाव धुमाळ' },
    { en: 'Tanali', mr: 'तान्हाळी' },
  ],
  malshiras: [
    { en: 'Akluj', mr: 'अकलूज' },
    { en: 'Natepute', mr: 'नातेपुते' },
    { en: 'Velapur', mr: 'वेळापूर' },
    { en: 'Sadashivnagar', mr: 'सदाशिवनगर' },
    { en: 'Malinagar', mr: 'माळीनगर' },
    { en: 'Borgaon Malshiras', mr: 'बोरगाव माळशिरस' },
    { en: 'Sangam Malshiras', mr: 'संगम माळशिरस' },
    { en: 'Piliv', mr: 'पिलीव' },
    { en: 'Dharmapuri', mr: 'धर्मापुरी' },
    { en: 'Dahigaon Malshiras', mr: 'दहिगाव माळशिरस' },
  ],
  barshi: [
    { en: 'Vairag', mr: 'वैराग' },
    { en: 'Pangri', mr: 'पांगरी' },
    { en: 'Dhotre', mr: 'धोत्रे' },
    { en: 'Tadwale', mr: 'ताडवळे' },
    { en: 'Upale Dumala', mr: 'उपळे दुमाला' },
    { en: 'Gaudgaon', mr: 'गौडगाव' },
    { en: 'Korphale', mr: 'कोरफळे' },
    { en: 'Kari Barshi', mr: 'कारी बार्शी' },
  ],
  karmala: [
    { en: 'Jeur', mr: 'जेऊर' },
    { en: 'Kem', mr: 'केम' },
    { en: 'Korti Karmala', mr: 'कोर्टी करमाळा' },
    { en: 'Pande', mr: 'पांडे' },
    { en: 'Wangi', mr: 'वांगी' },
    { en: 'Sade', mr: 'साडे' },
    { en: 'Pophlaj', mr: 'पोफळज' },
    { en: 'Kandar', mr: 'कंदर' },
    { en: 'Sapatne', mr: 'सपटणे' },
  ],
  madha: [
    { en: 'Kurduwadi', mr: 'कुर्डुवाडी' },
    { en: 'Tembhurni', mr: 'टेंभुर्णी' },
    { en: 'Modnimb', mr: 'मोडनिंब' },
    { en: 'Bhend', mr: 'भेंड' },
    { en: 'Nimgaon Madha', mr: 'निमगाव माढा' },
    { en: 'Upalai Madha', mr: 'उपळाई माढा' },
    { en: 'Ranje', mr: 'रांझे' },
  ],
  akkalkot: [
    { en: 'Maindargi', mr: 'मैंदर्गी' },
    { en: 'Chapalgaon', mr: 'चपळगाव' },
    { en: 'Wagdari', mr: 'वागदरी' },
    { en: 'Dudhani', mr: 'दुधनी' },
    { en: 'Karjal', mr: 'करजळ' },
    { en: 'Tadwal', mr: 'तडवळ' },
    { en: 'Tolnur', mr: 'तोलनूर' },
  ],
  sangole: [
    { en: 'Nazare', mr: 'नाझरे' },
    { en: 'Mahud', mr: 'महुद' },
    { en: 'Javala', mr: 'जवळा' },
    { en: 'Kole', mr: 'कोळे' },
    { en: 'Methwade', mr: 'मेथवडे' },
    { en: 'Watambare', mr: 'वाटंबरे' },
    { en: 'Gheradi', mr: 'घेराडी' },
    { en: 'Hatid', mr: 'हातीद' },
    { en: 'Wadegaon Sangola', mr: 'वाडेगाव सांगोला' },
  ],
  mohol: [
    { en: 'Angar', mr: 'अनगर' },
    { en: 'Kurul', mr: 'कुरुल' },
    { en: 'Pokharapur', mr: 'पोखरापूर' },
    { en: 'Kamati', mr: 'कामती' },
    { en: 'Begampur', mr: 'बेगमपूर' },
    { en: 'Malikpeth', mr: 'मलिकपेठ' },
    { en: 'Shirapur', mr: 'शिरापूर' },
    { en: 'Anvali', mr: 'अनवली' },
  ],

  // ── Kolhapur District ──────────────────────────────────────────────────────
  karvir: [
    { en: 'Uchgaon', mr: 'उचगाव' },
    { en: 'Vadanage', mr: 'वडणगे' },
    { en: 'Chikhali', mr: 'चिखली' },
    { en: 'Shiroli Du', mr: 'शिरोली दु.' },
    { en: 'Girgaon', mr: 'गिरगाव' },
    { en: 'Kalamba', mr: 'कळंबा' },
    { en: 'Pachgaon', mr: 'पाचगाव' },
    { en: 'Morewadi', mr: 'मोरेवाडी' },
    { en: 'Sarnobatwadi', mr: 'सरनोबतवाडी' },
    { en: 'Ispurli', mr: 'इस्पुर्ली' },
    { en: 'Haldi', mr: 'हळदी' },
    { en: 'Beed Karvir', mr: 'बीड करवीर' },
  ],
  hatkanangale: [
    { en: 'Hupari', mr: 'हुपरी' },
    { en: 'Shiroli', mr: 'शिरोली' },
    { en: 'Kodoli', mr: 'कोडोली' },
    { en: 'Herle', mr: 'हेरले' },
    { en: 'Rendal', mr: 'रेंदाळ' },
    { en: 'Pattankodoli', mr: 'पट्टणकोडोली' },
    { en: 'Alte', mr: 'आळते' },
    { en: 'Rukadi', mr: 'रुकडी' },
    { en: 'Vathar', mr: 'वाठार' },
    { en: 'Mangaon Hatkanangale', mr: 'माणगाव हातकणंगले' },
  ],
  shirol: [
    { en: 'Jaysingpur Gramin', mr: 'जयसिंगपूर ग्रामीण' },
    { en: 'Kurundwad Gramin', mr: 'कुरुंदवाड ग्रामीण' },
    { en: 'Dharangutti', mr: 'धरणगुत्ती' },
    { en: 'Nandre', mr: 'नांद्रे' },
    { en: 'Danoli', mr: 'दानोळी' },
    { en: 'Ganeshwadi', mr: 'गणेशवाडी' },
    { en: 'Nimshirgaon', mr: 'निमशिरगाव' },
    { en: 'Takali Shirol', mr: 'टाकळी शिरोळ' },
    { en: 'Udgaon', mr: 'उदगाव' },
    { en: 'Akiwat', mr: 'अकिवाट' },
  ],
  kagal: [
    { en: 'Senapati Kapshi', mr: 'सेनापती कापशी' },
    { en: 'Sidhnerli', mr: 'सिद्धनेर्ली' },
    { en: 'Bidri', mr: 'बिद्री' },
    { en: 'Murgud', mr: 'मुरगूड' },
    { en: 'Sulgaon', mr: 'सुलगाव' },
    { en: 'Kasaba Sangaon', mr: 'कसबा सांगाव' },
    { en: 'Vandur', mr: 'वांदूर' },
    { en: 'Bastawade Kagal', mr: 'बस्तवाडे कागल' },
    { en: 'Bamani', mr: 'बामणी' },
  ],
  panhala: [
    { en: 'Kodoli Panhala', mr: 'कोडोली पन्हाळा' },
    { en: 'Kale Panhala', mr: 'काळे पन्हाळा' },
    { en: 'Kotoli', mr: 'कोतोली' },
    { en: 'Borpadale', mr: 'बोरपाडळे' },
    { en: 'Padali Panhala', mr: 'पाडळी पन्हाळा' },
    { en: 'Ghotawade', mr: 'घोटवडे' },
    { en: 'Pohale', mr: 'पोहाळे' },
    { en: 'Majale', mr: 'माजले' },
  ],
  radhanagari: [
    { en: 'Tarale', mr: 'तारळे' },
    { en: 'Rashivade', mr: 'राशिवडे' },
    { en: 'Kaulav', mr: 'कौलव' },
    { en: 'Solankur', mr: 'सोळांकूर' },
    { en: 'Sarawade', mr: 'सरवडे' },
    { en: 'Kasaba Tarale', mr: 'कसबा तारळे' },
    { en: 'Shelewadi', mr: 'शेळेवाडी' },
  ],

  // ── Satara District ────────────────────────────────────────────────────────
  karad: [
    { en: 'Umbraj', mr: 'उंब्रज' },
    { en: 'Masur', mr: 'मसूर' },
    { en: 'Shenoli', mr: 'शेनोली' },
    { en: 'Kale Karad', mr: 'काले कराड' },
    { en: 'Ogalewadi', mr: 'ओगलेवाडी' },
    { en: 'Malkapur Karad', mr: 'मलकापूर कराड' },
    { en: 'Wing', mr: 'विंग' },
    { en: 'Saidapur', mr: 'सैदापूर' },
    { en: 'Kese', mr: 'केसे' },
    { en: 'Undale', mr: 'उंडाळे' },
    { en: 'Vasantgad', mr: 'वसंतगड' },
    { en: 'Charegaon', mr: 'चरेगाव' },
    { en: 'Supane', mr: 'सुपाणे' },
  ],
  wai: [
    { en: 'Bhuinj', mr: 'भुईंज' },
    { en: 'Pachwad', mr: 'पाचवड' },
    { en: 'Surur', mr: 'सुरुड' },
    { en: 'Menavali', mr: 'मेणवली' },
    { en: 'Dhom', mr: 'धोम' },
    { en: 'Kenjal', mr: 'केंजळ' },
    { en: 'Pasarni', mr: 'पसरणी' },
    { en: 'Bavdhan', mr: 'बावधन' },
    { en: 'Ozarde', mr: 'ओझर्डे' },
  ],
  phaltan: [
    { en: 'Taradgaon', mr: 'तरडगाव' },
    { en: 'Sakharwadi', mr: 'साखरवाडी' },
    { en: 'Vidani', mr: 'विडाणी' },
    { en: 'Barad', mr: 'बरड' },
    { en: 'Gunware', mr: 'गुणवरे' },
    { en: 'Nimblak Phaltan', mr: 'निंबळक फलटण' },
    { en: 'Adarki', mr: 'आदर्की' },
    { en: 'Girvi', mr: 'गिरवी' },
    { en: 'Hol Phaltan', mr: 'होळ फलटण' },
    { en: 'Asu', mr: 'आसू' },
    { en: 'Wathar Nimbalkar', mr: 'वाठार निंबाळकर' },
  ],
  khatav: [
    { en: 'Vaduj', mr: 'वडूज' },
    { en: 'Pusegaon', mr: 'पुसेगाव' },
    { en: 'Mayani', mr: 'मायणी' },
    { en: 'Pusesawali', mr: 'पुसेसावळी' },
    { en: 'Aundh', mr: 'औंध' },
    { en: 'Kuroli', mr: 'कुरोली' },
    { en: 'Diskal', mr: 'दिसकल' },
    { en: 'Daruj', mr: 'दारूज' },
    { en: 'Katarkhatav', mr: 'कतारखटाव' },
  ],

  // ── Sangli District ────────────────────────────────────────────────────────
  miraj: [
    { en: 'Kupwad Gramin', mr: 'कुपवाड ग्रामीण' },
    { en: 'Mhaisal', mr: 'म्हैसाळ' },
    { en: 'Bedag', mr: 'बेडग' },
    { en: 'Arjunwad', mr: 'अर्जुनवाड' },
    { en: 'Savali Miraj', mr: 'सावळी मिरज' },
    { en: 'Malgaon', mr: 'माळगाव' },
    { en: 'Bolwad', mr: 'बोळवाड' },
    { en: 'Haripur', mr: 'हरिपूर' },
    { en: 'Tanang', mr: 'ताणंग' },
  ],
  tasgaon: [
    { en: 'Savarde Tasgaon', mr: 'सावर्डे तासगाव' },
    { en: 'Vasumbe', mr: 'वासुंबे' },
    { en: 'Manjarde', mr: 'मांजर्डे' },
    { en: 'Nimani', mr: 'निमाणी' },
    { en: 'Chinchani Tasgaon', mr: 'चिंचणी तासगाव' },
    { en: 'Visapur Tasgaon', mr: 'विसापूर तासगाव' },
    { en: 'Jarandi', mr: 'जरांडी' },
    { en: 'Punadi', mr: 'पुनाडी' },
  ],
  walwa: [
    { en: 'Islampur Gramin', mr: 'इस्लामपूर ग्रामीण' },
    { en: 'Ashta', mr: 'आष्टा' },
    { en: 'Kasegaon Walwa', mr: 'कासेगाव वाळवा' },
    { en: 'Peth Walwa', mr: 'पेठ वाळवा' },
    { en: 'Kameri', mr: 'कामेरी' },
    { en: 'Takari', mr: 'ताकारी' },
    { en: 'Bahe', mr: 'बाहे' },
    { en: 'Yelur', mr: 'येळूर' },
    { en: 'Gotkhindi', mr: 'गोठखिंडी' },
    { en: 'Chikurde', mr: 'चिकुर्डे' },
  ],

  // ── Chhatrapati Sambhajinagar ──────────────────────────────────────────────
  paithan: [
    { en: 'Bidkin', mr: 'बिडकीन' },
    { en: 'Apegaon', mr: 'आपेगाव' },
    { en: 'Dhangarwadi', mr: 'धनगरवाडी' },
    { en: 'Balanagar', mr: 'बालानगर' },
    { en: 'Pachod', mr: 'पाचोड' },
    { en: 'Dhorkin', mr: 'धोरकीन' },
    { en: 'Isarwadi', mr: 'इसारवाडी' },
  ],
  gangapur: [
    { en: 'Lasur Station', mr: 'लासूर स्टेशन' },
    { en: 'Bhendala', mr: 'भेंडाळा' },
    { en: 'Shendurwada', mr: 'शेंदुरवाडा' },
    { en: 'Turkabad', mr: 'तुर्काबाद' },
    { en: 'Manjari Gangapur', mr: 'मांजरी गंगापूर' },
    { en: 'Jamgaon Gangapur', mr: 'जामगाव गंगापूर' },
  ],
  vaijapur: [
    { en: 'Rotegaon', mr: 'रोटेगाव' },
    { en: 'Borsar', mr: 'बोरसर' },
    { en: 'Khandala Vaijapur', mr: 'खंडाळा वैजापूर' },
    { en: 'Shivoor', mr: 'शिवूर' },
    { en: 'Ladgaon', mr: 'लाडगाव' },
    { en: 'Garaj', mr: 'गरज' },
    { en: 'Mahalgaon', mr: 'महाळगाव' },
    { en: 'Parsoda', mr: 'पारसोडा' },
  ],
  sillod: [
    { en: 'Ajintha (Ajanta)', mr: 'अजिंठा' },
    { en: 'Bharadi', mr: 'भराडी' },
    { en: 'Golegaon Sillod', mr: 'गोळेगाव सिल्लोड' },
    { en: 'Anvi', mr: 'अणवी' },
    { en: 'Palshi Sillod', mr: 'पळशी सिल्लोड' },
    { en: 'Kelgaon', mr: 'केळगाव' },
    { en: 'Undangaon', mr: 'उंदाणगाव' },
  ],
};

export async function seedProperVillages() {
  console.log('🚀 Seeding authentic, real Gram Panchayat villages into Neon PostgreSQL...');
  const startTime = Date.now();

  const talukas = await prisma.taluka.findMany({
    select: { id: true, code: true, nameEn: true, nameMr: true },
  });

  let insertedCount = 0;

  for (const taluka of talukas) {
    const key = taluka.nameEn.toLowerCase().replace(/[^a-z0-9]/g, '_');
    
    // Find matching specific real village list or use generic authentic set
    let villageList = PROPER_TALUKA_VILLAGES[key];

    if (!villageList) {
      // Find by substring match
      for (const [k, vList] of Object.entries(PROPER_TALUKA_VILLAGES)) {
        if (key.includes(k) || k.includes(key)) {
          villageList = vList;
          break;
        }
      }
    }

    if (villageList && villageList.length > 0) {
      const records = villageList.map((v, idx) => ({
        code: `${taluka.code}_real_${idx + 1}`,
        talukaId: taluka.id,
        nameEn: v.en,
        nameMr: v.mr,
        nameHi: v.hi || v.mr,
      }));

      const res = await prisma.village.createMany({
        data: records,
        skipDuplicates: true,
      });
      insertedCount += res.count;
    }
  }

  const finalTotal = await prisma.village.count();
  const duration = ((Date.now() - startTime) / 1000).toFixed(2);
  console.log(`✅ Proper villages seeded in ${duration}s! Total in DB: ${finalTotal} (Added ${insertedCount} proper villages)`);
}

if (require.main === module) {
  seedProperVillages()
    .then(async () => {
      await prisma.$disconnect();
      process.exit(0);
    })
    .catch(async (e) => {
      console.error('❌ Error seeding proper villages:', e);
      await prisma.$disconnect();
      process.exit(1);
    });
}
